### ISSUE TITLE
Is the method applicable to WES data？

### ISSUE THREAD

**Issue by potato-digger** [VerenaK90/Neuroblastoma_evolution#5]
I'm curious to know if your method _Neuroblastoma_evolution_ is equally applicable to WES (Whole Exome Sequencing) data. Specifically, I am wondering if your method can be applied to the analysis and interpretation of WES data. I am intrigued by your research as I believe it may offer valuable insights for my current research project.
Thank you very much for your time. I look forward to your response!

**Comment by VerenaK90** [comment]
Hello, thank you for your interest in my work! Unfortunately, I wouldn't recommend using Neuroblastoma_evolution on WES data, as they are likely too sparse to confidently estimate mutation times. Happy to discuss potential options further, do drop me an email if you are interested!

**Comment by potato-digger** [comment]
Thank you so much for your reply. Actually, I also encountered this issue while attempting to use the Neuroblastoma_evolution on WES data from TCGA. The results indicated significant variations in MRCA Timing between different patients, raising concerns about the reliability of the computed results. To address this issue, I employed the following approach: when calculating segment SSNV density, I utilized the lengths of all exonic regions within the segment rather than the entire segment length. This adjustment aims to correct for mutation density. Do you think this approach is feasible? And I have another question. When calculating SSNV density, do these mutations include driver mutations?

**Comment by VerenaK90** [comment]
Yes, the SNV density is computed from all SSNVs, including drivers (it actually doesn't distinguish between drivers and passengers). However, I think the uncertainty remains the same if you only use exons, as you have an overall short segment length + few mutations in absolute counts, which will translate into a high uncertainty of the true SNV density.

**Comment by potato-digger** [comment]
Got it, thanks for your patience. Even though there might not be a perfect solution, I'll make sure to keep this in mind for future data exploration. Thank you so much again for your response!^o^
